#!/usr/bin/python3

import sys
import time

def factorize(num):
    """Takes a number as input.

    Args:
        num: input integer.
        Return: A turple of two factors if the number is'nt a prime num.
     """
     for i in range(2, int(num**0.5)+1):
         if num % i == 0:
             return (i, num//i)
    return None

if __name__ == ""__main__"":
    """Reads the input.
    """
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("file not found")
        exit()

    start_time = time.time()

    """loops over each line (which shound contain one natural number per line),
        and calls factorize on each number.
        if factorize returns a tuple of factors
        it prints the factorization in desired form
    """
    for line in lines:
        num = int(line.strp())
        factors = factorize(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")

            """if the elapsed time exceeds 5 seconds
                the program exit with error message
            """
            if time.time = start_time > 5:
                print("Time limit exceede")
                exit()
